"""Generate site/src/lib/skillspectorRules.generated.ts from SkillSpector.

This pulls ``DEFAULT_EXPLANATIONS`` and the rough rule -> category mapping
out of the installed SkillSpector package and writes a TypeScript module
the React site imports. Re-run after upgrading SkillSpector:

    .venv/bin/python scripts/gen_rule_catalog.py

The output is committed so the site builds without a Python toolchain.
"""

from __future__ import annotations

import json
from pathlib import Path

from skillspector.nodes.analyzers import pattern_defaults as pd

# Hand-curated rule -> PatternCategory mapping. The static analyzer source
# files don't expose this directly per-rule, so we keep an explicit table.
# When SkillSpector adds rules, edit this dict and rerun the script.
CATEGORIES: dict[str, str] = {
    # Prompt injection family
    "P1": "PROMPT_INJECTION",
    "P2": "PROMPT_INJECTION",
    "P3": "DATA_EXFILTRATION",
    "P4": "PROMPT_INJECTION",
    "P5": "PROMPT_INJECTION",
    # System prompt leakage
    "P6": "SYSTEM_PROMPT_LEAKAGE",
    "P7": "SYSTEM_PROMPT_LEAKAGE",
    "P8": "SYSTEM_PROMPT_LEAKAGE",
    # Data exfiltration
    "E1": "DATA_EXFILTRATION",
    "E2": "DATA_EXFILTRATION",
    "E3": "DATA_EXFILTRATION",
    "E4": "DATA_EXFILTRATION",
    # Privilege escalation
    "PE1": "PRIVILEGE_ESCALATION",
    "PE2": "PRIVILEGE_ESCALATION",
    "PE3": "PRIVILEGE_ESCALATION",
    # Supply chain
    "SC1": "SUPPLY_CHAIN",
    "SC2": "SUPPLY_CHAIN",
    "SC3": "SUPPLY_CHAIN",
    "SC4": "SUPPLY_CHAIN",
    "SC5": "SUPPLY_CHAIN",
    "SC6": "SUPPLY_CHAIN",
    # Excessive agency
    "EA1": "EXCESSIVE_AGENCY",
    "EA2": "EXCESSIVE_AGENCY",
    "EA3": "EXCESSIVE_AGENCY",
    "EA4": "EXCESSIVE_AGENCY",
    # Output handling
    "OH1": "OUTPUT_HANDLING",
    "OH2": "OUTPUT_HANDLING",
    "OH3": "OUTPUT_HANDLING",
    # Memory poisoning
    "MP1": "MEMORY_POISONING",
    "MP2": "MEMORY_POISONING",
    "MP3": "MEMORY_POISONING",
    # Tool misuse
    "TM1": "TOOL_MISUSE",
    "TM2": "TOOL_MISUSE",
    "TM3": "TOOL_MISUSE",
    # Rogue agent
    "RA1": "ROGUE_AGENT",
    "RA2": "ROGUE_AGENT",
    # Trigger abuse
    "TR1": "TRIGGER_ABUSE",
    "TR2": "TRIGGER_ABUSE",
    "TR3": "TRIGGER_ABUSE",
    # Behavioural taint tracking
    "TT1": "DATA_EXFILTRATION",
    "TT2": "DATA_EXFILTRATION",
    "TT3": "DATA_EXFILTRATION",
    "TT4": "DATA_EXFILTRATION",
    "TT5": "PROMPT_INJECTION",
    # Behavioural AST
    "AST1": "TOOL_MISUSE",
    "AST2": "TOOL_MISUSE",
    "AST3": "TOOL_MISUSE",
    "AST4": "TOOL_MISUSE",
    "AST5": "TOOL_MISUSE",
    "AST6": "TOOL_MISUSE",
    "AST7": "TOOL_MISUSE",
    "AST8": "TOOL_MISUSE",
    # YARA matches
    "YR1": "YARA_MATCH",
    "YR2": "YARA_MATCH",
    "YR3": "YARA_MATCH",
    "YR4": "YARA_MATCH",
    # MCP least privilege
    "LP1": "MCP_LEAST_PRIVILEGE",
    "LP2": "MCP_LEAST_PRIVILEGE",
    "LP3": "MCP_LEAST_PRIVILEGE",
    "LP4": "MCP_LEAST_PRIVILEGE",
    # MCP tool poisoning
    "TP1": "MCP_TOOL_POISONING",
    "TP2": "MCP_TOOL_POISONING",
    "TP3": "MCP_TOOL_POISONING",
    "TP4": "MCP_TOOL_POISONING",
}


def _category_label(key: str) -> str:
    try:
        return pd.PatternCategory[key].value
    except KeyError:
        return key.replace("_", " ").title()


def build_catalog() -> dict[str, dict[str, str]]:
    catalog: dict[str, dict[str, str]] = {}
    for rule, description in pd.DEFAULT_EXPLANATIONS.items():
        cat_key = CATEGORIES.get(rule, "")
        catalog[rule] = {
            "id": rule,
            "category": _category_label(cat_key) if cat_key else "",
            "description": description.strip(),
        }
    return dict(sorted(catalog.items()))


def render_ts(catalog: dict[str, dict[str, str]]) -> str:
    """Render the TS module the React site imports."""
    body = json.dumps(catalog, indent=2)
    return (
        "// AUTO-GENERATED by scripts/gen_rule_catalog.py.\n"
        "// Source: skillspector.nodes.analyzers.pattern_defaults.\n"
        "// Re-run after upgrading SkillSpector.\n"
        "\n"
        "export interface SkillSpectorRule {\n"
        "  id: string;\n"
        "  category: string;\n"
        "  description: string;\n"
        "}\n"
        "\n"
        f"export const SKILLSPECTOR_RULES: Record<string, SkillSpectorRule> = {body};\n"
    )


def main() -> int:
    catalog = build_catalog()
    out = Path(__file__).resolve().parent.parent / "site" / "src" / "lib" / "skillspectorRules.generated.ts"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_ts(catalog), encoding="utf-8")
    print(f"wrote {out} ({len(catalog)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
